version: '2'
services:
    # receive http connection from client
    web:
        image: nginx
        restart: always
        volumes:
            - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
            - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
        ports:
            - 80:80
            - 443:443

